/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.*;
import DAL.*;
import Entities.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxs18
 */
public class HomeUserUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdminUI
     */
    public HomeUserUI() {
        initComponents();
        setLocationRelativeTo(null);

    }
    int width = 210;
    int height = 550;
    int dongChon = -1;

    void openMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    pnMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeUserUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--) {
                    pnMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeUserUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public void loadTableSach() {
        tbSach.setModel(new SachBLL(SachDAL.listSach()));
    }

    public void loadTableGioHang() {
        tbGioHang.setModel(new GioHangBLL(GioHangDAL.listGioHangNow(DangNhapUI.username)));
    }

    public void loadTongTien() {
        DecimalFormat f = new DecimalFormat("###,###,###");
        lbTongTienGioHang.setText(f.format(GioHangDAL.tongTien(DangNhapUI.username)) + " VNĐ");
    }

    public void loadKhachHang() {
        KhachHang kh = KhachHangDAL.getKhachHang(DangNhapUI.username);
        if (kh != null) {
            txtHoTenKH.setText(kh.getHoTen());
            txtSoDTKH.setText(kh.getSoDT());
            txtEmailKH.setText(kh.getEmail());
            txtDiaChiKH.setText(kh.getDiaChi());
        }
    }
    
    public void loadTableDatHang(){
        tbDatHang.setModel(new GioHangBLL(GioHangDAL.listGioHangNow(DangNhapUI.username)));
    }
    
    public void loadTongTienDatHang() {
        DecimalFormat f = new DecimalFormat("###,###,###");
        lbTongTienDatHang.setText(f.format(GioHangDAL.tongTien(DangNhapUI.username)) + " VNĐ");
    }
    
    public void loadKhachHangDatHang() {
        KhachHang kh = KhachHangDAL.getKhachHang(DangNhapUI.username);
        if (kh != null) {
            txtHoTenDH.setText(kh.getHoTen());
            txtSoDTDH.setText(kh.getSoDT());
            txtEmailDH.setText(kh.getEmail());
            txtDiaChiDH.setText(kh.getDiaChi());
        }
    }

    public void chonDongSach() {
        dongChon = tbSach.getSelectedRow();
        if (dongChon != -1) {
            Sach s = SachDAL.listSach().get(dongChon);
            txtMaSach1.setText(tbSach.getValueAt(dongChon, 1).toString());
            txtTenSach1.setText(tbSach.getValueAt(dongChon, 2).toString());
            txtTacGia1.setText(tbSach.getValueAt(dongChon, 3).toString());
            txtNhaXuatBan1.setText(tbSach.getValueAt(dongChon, 4).toString());
            txtNamXuatBan1.setText(tbSach.getValueAt(dongChon, 5).toString());
            txtSoTrang1.setText(tbSach.getValueAt(dongChon, 6).toString());
            txtDonGia1.setText(tbSach.getValueAt(dongChon, 7).toString());
            txtSoLuongCon1.setText(tbSach.getValueAt(dongChon, 8).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbTrangChu = new javax.swing.JLabel();
        lbSanPham = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbDong = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        openMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TrangChu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DanhSachSanPham = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaSach1 = new javax.swing.JTextField();
        txtTenSach1 = new javax.swing.JTextField();
        txtTacGia1 = new javax.swing.JTextField();
        txtNhaXuatBan1 = new javax.swing.JTextField();
        txtSoLuongDat1 = new javax.swing.JTextField();
        txtNamXuatBan1 = new javax.swing.JTextField();
        txtSoTrang1 = new javax.swing.JTextField();
        txtDonGia1 = new javax.swing.JTextField();
        txtSoLuongCon1 = new javax.swing.JTextField();
        txtTim1 = new javax.swing.JTextField();
        btnTim1 = new javax.swing.JButton();
        btnLamMoi1 = new javax.swing.JButton();
        btnThemGio1 = new javax.swing.JButton();
        GioHang = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGioHang = new javax.swing.JTable();
        btnXoaGioHang = new javax.swing.JButton();
        btnXoaTatCaGioHang = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lbTongTienGioHang = new javax.swing.JLabel();
        btnDatHang = new javax.swing.JButton();
        DatHang = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtHoTenDH = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtSoDTDH = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtEmailDH = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDiaChiDH = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDatHang = new javax.swing.JTable();
        btnQuayLaiGioHang = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lbTongTienDatHang = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtHoTenKH = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSoDTKH = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEmailKH = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDiaChiKH = new javax.swing.JTextField();
        btnCapNhatKH = new javax.swing.JButton();
        lbGioHang = new javax.swing.JLabel();
        lbTaiKhoan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangChu.setText("Trang chủ");
        lbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseClicked(evt);
            }
        });
        pnMenu.add(lbTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 210, 43));

        lbSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSanPham.setText("Danh sách sản phẩm");
        lbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSanPhamMouseClicked(evt);
            }
        });
        pnMenu.add(lbSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 210, 43));

        lbDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangXuat.setText("Đăng xuất");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
        });
        pnMenu.add(lbDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 455, 210, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-menu (2).jpg"))); // NOI18N
        pnMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 42, -1, -1));

        lbDong.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbDong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDong.setText("X");
        lbDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDongMouseClicked(evt);
            }
        });
        pnMenu.add(lbDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 6, 30, -1));
        pnMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 392, 210, 10));
        pnMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 210, 10));

        jPanel1.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 550));

        openMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        openMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuMouseClicked(evt);
            }
        });
        jPanel1.add(openMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 21, -1, -1));

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRANG CHỦ");

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        jPanel4.add(TrangChu, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DANH SÁCH SẢN PHẨM");

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSach);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm theo tên sách:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã sách:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên sách:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tác giả:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nhà xuất bản:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Năm xuất bản:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số trang:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Đơn giá:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Số lượng còn:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Số lượng đặt:");

        txtMaSach1.setEditable(false);

        txtTenSach1.setEditable(false);

        txtTacGia1.setEditable(false);

        txtNhaXuatBan1.setEditable(false);

        txtNamXuatBan1.setEditable(false);

        txtSoTrang1.setEditable(false);

        txtDonGia1.setEditable(false);

        txtSoLuongCon1.setEditable(false);

        btnTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search1.jpg"))); // NOI18N
        btnTim1.setText("Tìm kiếm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });

        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh 1.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        btnThemGio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.jpg"))); // NOI18N
        btnThemGio1.setText("Thêm vào giỏ hàng");
        btnThemGio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DanhSachSanPhamLayout = new javax.swing.GroupLayout(DanhSachSanPham);
        DanhSachSanPham.setLayout(DanhSachSanPhamLayout);
        DanhSachSanPhamLayout.setHorizontalGroup(
            DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenSach1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtTacGia1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtNhaXuatBan1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtMaSach1)
                            .addComponent(txtSoLuongDat1))
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnThemGio1))
                            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(btnTim1))
                                .addGap(18, 18, 18)
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamXuatBan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoLuongCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnLamMoi1)))))
                    .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DanhSachSanPhamLayout.setVerticalGroup(
            DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnTim1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNhaXuatBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtMaSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNamXuatBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))))
                    .addComponent(btnLamMoi1)
                    .addGroup(DanhSachSanPhamLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txtSoTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuongCon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSoLuongDat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemGio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(DanhSachSanPham, "card3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("GIỎ HÀNG");

        tbGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbGioHang);

        btnXoaGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnXoaGioHang.setText("Xóa");
        btnXoaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaGioHangActionPerformed(evt);
            }
        });

        btnXoaTatCaGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        btnXoaTatCaGioHang.setText("Xóa tất cả");
        btnXoaTatCaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaGioHangActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Tổng tiền:");

        lbTongTienGioHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTongTienGioHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTongTienGioHang.setText("Tổng Tiền");

        btnDatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order.png"))); // NOI18N
        btnDatHang.setText("Đặt hàng");
        btnDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GioHangLayout = new javax.swing.GroupLayout(GioHang);
        GioHang.setLayout(GioHangLayout);
        GioHangLayout.setHorizontalGroup(
            GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GioHangLayout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GioHangLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongTienGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangLayout.createSequentialGroup()
                        .addComponent(btnXoaGioHang)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GioHangLayout.createSequentialGroup()
                        .addGroup(GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaTatCaGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        GioHangLayout.setVerticalGroup(
            GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GioHangLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGroup(GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GioHangLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnXoaGioHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaTatCaGioHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnDatHang))
                    .addGroup(GioHangLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTienGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel4.add(GioHang, "card4");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("ĐẶT HÀNG");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setText("Họ và tên:");

        txtHoTenDH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("Số điện thoại:");

        txtSoDTDH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setText("Email:");

        txtEmailDH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("Địa chỉ:");

        txtDiaChiDH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tbDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDatHang);

        btnQuayLaiGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back1.png"))); // NOI18N
        btnQuayLaiGioHang.setText("Quay lại giỏ hàng");
        btnQuayLaiGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiGioHangActionPerformed(evt);
            }
        });

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.jpg"))); // NOI18N
        btnThanhToan.setText("Thanh toán");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setText("Tổng tiền:");

        lbTongTienDatHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTongTienDatHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTongTienDatHang.setText("Tổng Tiền");

        javax.swing.GroupLayout DatHangLayout = new javax.swing.GroupLayout(DatHang);
        DatHang.setLayout(DatHangLayout);
        DatHangLayout.setHorizontalGroup(
            DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatHangLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatHangLayout.createSequentialGroup()
                .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatHangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTongTienDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatHangLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChiDH)
                            .addComponent(txtEmailDH)
                            .addComponent(txtSoDTDH)
                            .addGroup(DatHangLayout.createSequentialGroup()
                                .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addGroup(DatHangLayout.createSequentialGroup()
                                        .addComponent(btnQuayLaiGioHang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnThanhToan)))
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addComponent(txtHoTenDH))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        DatHangLayout.setVerticalGroup(
            DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatHangLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(40, 40, 40)
                .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatHangLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoTenDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoDTDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaChiDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQuayLaiGioHang)
                            .addComponent(btnThanhToan)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lbTongTienDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.add(DatHang, "card5");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("THÔNG TIN CÁ NHÂN");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setText("Họ và tên");

        txtHoTenKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setText("Số điện thoại");

        txtSoDTKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setText("Email");

        txtEmailKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setText("Địa chỉ");

        txtDiaChiKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        btnCapNhatKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhatKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btnCapNhatKH.setText("Cập nhật");
        btnCapNhatKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaiKhoanLayout.createSequentialGroup()
                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TaiKhoanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TaiKhoanLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTenKH)
                            .addComponent(txtSoDTKH)
                            .addComponent(txtEmailKH)
                            .addGroup(TaiKhoanLayout.createSequentialGroup()
                                .addGroup(TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 181, Short.MAX_VALUE))
                            .addComponent(txtDiaChiKH))))
                .addGap(319, 319, 319))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaiKhoanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCapNhatKH)
                .addGap(419, 419, 419))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(26, 26, 26)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhatKH)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        jPanel4.add(TaiKhoan, "card6");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 988, 484));

        lbGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart.png"))); // NOI18N
        lbGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGioHangMouseClicked(evt);
            }
        });
        jPanel1.add(lbGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 30, 30));

        lbTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile-user1.png"))); // NOI18N
        lbTaiKhoan.setText("Tài Khoản");
        lbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTaiKhoanMouseClicked(evt);
            }
        });
        jPanel1.add(lbTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuMouseClicked
        // TODO add your handling code here:
        openMenu();
    }//GEN-LAST:event_openMenuMouseClicked

    private void lbDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDongMouseClicked
        // TODO add your handling code here:
        closeMenu();
    }//GEN-LAST:event_lbDongMouseClicked

    private void lbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(true);
        DanhSachSanPham.setVisible(false);
        TaiKhoan.setVisible(false);
        GioHang.setVisible(false);
        DatHang.setVisible(false);
    }//GEN-LAST:event_lbTrangChuMouseClicked

    private void lbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSanPhamMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        DanhSachSanPham.setVisible(true);
        TaiKhoan.setVisible(false);
        GioHang.setVisible(false);
        DatHang.setVisible(false);
        loadTableSach();
    }//GEN-LAST:event_lbSanPhamMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked
        // TODO add your handling code here:
        DangNhapUI dn = new DangNhapUI();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbDangXuatMouseClicked

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked
        // TODO add your handling code here:
        chonDongSach();
    }//GEN-LAST:event_tbSachMouseClicked

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> timSach = new ArrayList<>();
        for (var item : SachDAL.listSach()) {
            if (item.getTenSach().equalsIgnoreCase(txtTim1.getText())) {
                timSach.add(item);
            }
        }

        tbSach.setModel(new SachBLL(timSach));
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
        delTbSach();
        loadTableSach();
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void lbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTaiKhoanMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        DanhSachSanPham.setVisible(false);
        TaiKhoan.setVisible(true);
        GioHang.setVisible(false);
        DatHang.setVisible(false);
        loadKhachHang();
    }//GEN-LAST:event_lbTaiKhoanMouseClicked

    private void lbGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGioHangMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        DanhSachSanPham.setVisible(false);
        TaiKhoan.setVisible(false);
        GioHang.setVisible(true);
        DatHang.setVisible(false);
        loadTableGioHang();
        loadTongTien();
    }//GEN-LAST:event_lbGioHangMouseClicked

    private void btnThemGio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGio1ActionPerformed
        // TODO add your handling code here:
        dongChon = tbSach.getSelectedRow();
        if (dongChon != -1) {
            try {
                Sach s = SachDAL.listSach().get(dongChon);
                int soLuongDat = Integer.parseInt(txtSoLuongDat1.getText());
                if (soLuongDat <= s.getSoLuongCon()) {
                    GioHang gh = new GioHang();
                    gh.setMaTaiKhoan(DangNhapUI.username);
                    gh.setSachChon(s);
                    gh.setSoLuong(soLuongDat);
                    ArrayList<GioHang> listGh = GioHangDAL.listGioHang();
                    if (GioHangDAL.insert(listGh, gh)) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm vào giỏ hàng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        loadTableSach();
                        delTbSach();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Số lượng đặt lớn hơn số lượng có", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng đặt phải là số", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sản phẩm cần thêm", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemGio1ActionPerformed

    private void btnXoaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaGioHangActionPerformed
        // TODO add your handling code here:
        try {
            dongChon = tbGioHang.getSelectedRow();
            if (dongChon != -1) {
                GioHang gh = GioHangDAL.listGioHangNow(DangNhapUI.username).get(dongChon);
                int rs = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa ?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (rs == JOptionPane.YES_OPTION) {
                    if (GioHangDAL.delete(GioHangDAL.listGioHang(), gh)) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        loadTableGioHang();
                        loadTongTien();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sản phẩm để xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger("HoaDonBan.DAT", ex.getMessage());
//            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnXoaGioHangActionPerformed

    private void btnXoaTatCaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaGioHangActionPerformed
        // TODO add your handling code here:
        int rs = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa tất cả sản phẩm khỏi giỏ hàng", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (rs == JOptionPane.YES_OPTION) {
            try {
                GioHangDAL.deleteAll(GioHangDAL.listGioHang());
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableGioHang();
                loadTongTien();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaTatCaGioHangActionPerformed

    private void btnDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatHangActionPerformed
        // TODO add your handling code here:
        if (GioHangDAL.listGioHangNow(DangNhapUI.username).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Chưa có sản phẩm trong giỏ hàng", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            TrangChu.setVisible(false);
            DanhSachSanPham.setVisible(false);
            TaiKhoan.setVisible(false);
            GioHang.setVisible(false);
            DatHang.setVisible(true);
            loadKhachHangDatHang();
            loadTableDatHang();
            loadTongTienDatHang();
        }
    }//GEN-LAST:event_btnDatHangActionPerformed

    private void btnCapNhatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatKHActionPerformed
        try {
            KhachHang kh = new KhachHang();
            kh.setMaTK(DangNhapUI.username);
            kh.setHoTen(txtHoTenKH.getText());
            kh.setSoDT(txtSoDTKH.getText());
            kh.setEmail(txtEmailKH.getText());
            kh.setDiaChi(txtDiaChiKH.getText());
            if (KhachHangDAL.update(KhachHangDAL.listKhachHang(), kh)) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadKhachHang();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCapNhatKHActionPerformed

    private void btnQuayLaiGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiGioHangActionPerformed
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        DanhSachSanPham.setVisible(false);
        TaiKhoan.setVisible(false);
        GioHang.setVisible(true);
        DatHang.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiGioHangActionPerformed

    public void delTbSach() {
        txtMaSach1.setText("");
        txtTenSach1.setText("");
        txtTacGia1.setText("");
        txtNhaXuatBan1.setText("");
        txtNamXuatBan1.setText("");
        txtSoTrang1.setText("");
        txtDonGia1.setText("");
        txtSoLuongCon1.setText("");
        txtTim1.setText("");
        txtSoLuongDat1.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DanhSachSanPham;
    private javax.swing.JPanel DatHang;
    private javax.swing.JPanel GioHang;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JButton btnCapNhatKH;
    private javax.swing.JButton btnDatHang;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnQuayLaiGioHang;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemGio1;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnXoaGioHang;
    private javax.swing.JButton btnXoaTatCaGioHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbDong;
    private javax.swing.JLabel lbGioHang;
    private javax.swing.JLabel lbSanPham;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTongTienDatHang;
    private javax.swing.JLabel lbTongTienGioHang;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JLabel openMenu;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTable tbDatHang;
    private javax.swing.JTable tbGioHang;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtDiaChiDH;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtEmailDH;
    private javax.swing.JTextField txtEmailKH;
    private javax.swing.JTextField txtHoTenDH;
    private javax.swing.JTextField txtHoTenKH;
    private javax.swing.JTextField txtMaSach1;
    private javax.swing.JTextField txtNamXuatBan1;
    private javax.swing.JTextField txtNhaXuatBan1;
    private javax.swing.JTextField txtSoDTDH;
    private javax.swing.JTextField txtSoDTKH;
    private javax.swing.JTextField txtSoLuongCon1;
    private javax.swing.JTextField txtSoLuongDat1;
    private javax.swing.JTextField txtSoTrang1;
    private javax.swing.JTextField txtTacGia1;
    private javax.swing.JTextField txtTenSach1;
    private javax.swing.JTextField txtTim1;
    // End of variables declaration//GEN-END:variables
}
