/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.*;
import DAL.*;
import Entities.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxs18
 */
public class HomeAdminUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdminUI
     */
    public HomeAdminUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    int width = 210;
    int height = 550;
    int dongChon = -1;

    void openMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    pnMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeAdminUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    void closeMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--) {
                    pnMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeAdminUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public void loadTableSach() {
        tbSach.setModel(new SachBLL(SachDAL.listSach()));
    }

    public void loadTableTaiKhoan() {
        tbTaiKhoan.setModel(new TaiKhoanBLL(TaiKhoanDAL.listTaiKhoan()));
    }

    public void chonDongTbSach() {
        dongChon = tbSach.getSelectedRow();
        if (dongChon != -1) {
            txtMaSach1.setText(tbSach.getValueAt(dongChon, 1).toString());
            txtTenSach1.setText(tbSach.getValueAt(dongChon, 2).toString());
            txtTacGia1.setText(tbSach.getValueAt(dongChon, 3).toString());
            txtNhaXuatBan1.setText(tbSach.getValueAt(dongChon, 4).toString());
            txtNamXuatBan1.setText(tbSach.getValueAt(dongChon, 5).toString());
            txtSoTrang1.setText(tbSach.getValueAt(dongChon, 6).toString());
            txtDonGia1.setText(tbSach.getValueAt(dongChon, 7).toString());
            txtSoLuongCon1.setText(tbSach.getValueAt(dongChon, 8).toString());
        }
    }

    public void chonDongTbTaiKhoan() {
        dongChon = tbTaiKhoan.getSelectedRow();
        if (dongChon != -1) {
            txtTaiKhoanQLTK.setText(tbTaiKhoan.getValueAt(dongChon, 1).toString());
            txtMatKhauQLTK.setText(tbTaiKhoan.getValueAt(dongChon, 2).toString());
            txtVaiTroQLTK.setText(tbTaiKhoan.getValueAt(dongChon, 3).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbQuanLyDonHang = new javax.swing.JLabel();
        lbTrangChu = new javax.swing.JLabel();
        lbQuanLySanPham = new javax.swing.JLabel();
        lbQuanLyTaiKhoan = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbDong = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        openMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TrangChu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        QuanLySanPham = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenSach1 = new javax.swing.JTextField();
        txtNamXuatBan1 = new javax.swing.JTextField();
        txtSoTrang1 = new javax.swing.JTextField();
        txtDonGia1 = new javax.swing.JTextField();
        txtTacGia1 = new javax.swing.JTextField();
        txtSoLuongCon1 = new javax.swing.JTextField();
        btnXoa1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnCapNhat1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTim1 = new javax.swing.JTextField();
        btnTim1 = new javax.swing.JButton();
        btnLamMoi1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtMaSach1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNhaXuatBan1 = new javax.swing.JTextField();
        QuanLyDonHang = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        QuanLyTaiKhoan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTaiKhoanQLTK = new javax.swing.JTextField();
        txtMatKhauQLTK = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtVaiTroQLTK = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTimQLTK = new javax.swing.JTextField();
        btnTim2 = new javax.swing.JButton();
        btnLamMoi2 = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();
        btnCapNhat2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        ThongKe = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbQuanLyDonHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbQuanLyDonHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyDonHang.setText("Quản lý đơn hàng");
        lbQuanLyDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyDonHangMouseClicked(evt);
            }
        });
        pnMenu.add(lbQuanLyDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 210, 43));

        lbTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangChu.setText("Trang chủ");
        lbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseClicked(evt);
            }
        });
        pnMenu.add(lbTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 210, 43));

        lbQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbQuanLySanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLySanPham.setText("Quản lý sản phẩm");
        lbQuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLySanPhamMouseClicked(evt);
            }
        });
        pnMenu.add(lbQuanLySanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 210, 43));

        lbQuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbQuanLyTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyTaiKhoan.setText("Quản lý tài khoản");
        lbQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuanLyTaiKhoanMouseClicked(evt);
            }
        });
        pnMenu.add(lbQuanLyTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 294, 210, 43));

        lbDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangXuat.setText("Đăng xuất");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
        });
        pnMenu.add(lbDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 455, 210, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-menu (2).jpg"))); // NOI18N
        pnMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 42, -1, -1));

        lbDong.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbDong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDong.setText("X");
        lbDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDongMouseClicked(evt);
            }
        });
        pnMenu.add(lbDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 6, 30, -1));

        lbThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongKe.setText("Thống kê");
        lbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThongKeMouseClicked(evt);
            }
        });
        pnMenu.add(lbThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 210, 43));
        pnMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 392, 210, 10));
        pnMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 210, 10));

        jPanel1.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 550));

        openMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        openMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuMouseClicked(evt);
            }
        });
        jPanel1.add(openMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 21, -1, -1));

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRANG CHỦ");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-home.png"))); // NOI18N

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel13))
                    .addGroup(TrangChuLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel4.add(TrangChu, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUẢN LÝ SẢN PHẨM");

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSach);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên sách:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tác giả:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Năm xuất bản:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số trang:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đơn giá:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng còn:");

        btnXoa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnThem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.jpg"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnCapNhat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btnCapNhat1.setText("Cập nhật");
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tìm kiếm theo tên sách:");

        btnTim1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search1.jpg"))); // NOI18N
        btnTim1.setText("Tìm kiếm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });

        btnLamMoi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh 1.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã sách:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nhà xuất bản:");

        javax.swing.GroupLayout QuanLySanPhamLayout = new javax.swing.GroupLayout(QuanLySanPham);
        QuanLySanPham.setLayout(QuanLySanPhamLayout);
        QuanLySanPhamLayout.setHorizontalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(341, 341, 341)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuongCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhaXuatBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)
                                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamXuatBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel10)
                                .addGap(25, 25, 25)
                                .addComponent(txtTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnTim1)))
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnThem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapNhat1)
                .addGap(214, 214, 214)
                .addComponent(btnXoa1)
                .addGap(172, 172, 172))
            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        QuanLySanPhamLayout.setVerticalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLamMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(txtMaSach1)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNhaXuatBan1))
                .addGap(14, 14, 14)
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtSoTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSoLuongCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtTenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTacGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNamXuatBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat1)
                    .addComponent(btnXoa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(QuanLySanPhamLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(btnThem1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(QuanLySanPham, "card3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("QUẢN LÝ ĐƠN HÀNG");

        javax.swing.GroupLayout QuanLyDonHangLayout = new javax.swing.GroupLayout(QuanLyDonHang);
        QuanLyDonHang.setLayout(QuanLyDonHangLayout);
        QuanLyDonHangLayout.setHorizontalGroup(
            QuanLyDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyDonHangLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(371, 371, 371))
        );
        QuanLyDonHangLayout.setVerticalGroup(
            QuanLyDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDonHangLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        jPanel4.add(QuanLyDonHang, "card4");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("QUẢN LÝ TÀI KHOẢN");

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTaiKhoan);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Tài khoản:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Mật khẩu:");

        txtTaiKhoanQLTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMatKhauQLTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Vai trò:");

        txtVaiTroQLTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Tìm kiếm theo tên tài khoản:");

        txtTimQLTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTim2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search1.jpg"))); // NOI18N
        btnTim2.setText("Tìm kiếm");
        btnTim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim2ActionPerformed(evt);
            }
        });

        btnLamMoi2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh 1.png"))); // NOI18N
        btnLamMoi2.setText("Làm mới");
        btnLamMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi2ActionPerformed(evt);
            }
        });

        btnThem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.jpg"))); // NOI18N
        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnCapNhat2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btnCapNhat2.setText("Cập nhật");
        btnCapNhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat2ActionPerformed(evt);
            }
        });

        btnXoa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyTaiKhoanLayout = new javax.swing.GroupLayout(QuanLyTaiKhoan);
        QuanLyTaiKhoan.setLayout(QuanLyTaiKhoanLayout);
        QuanLyTaiKhoanLayout.setHorizontalGroup(
            QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(35, 35, 35)
                                .addComponent(txtVaiTroQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtTaiKhoanQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyTaiKhoanLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtMatKhauQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTim2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi2))
                    .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhat2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        QuanLyTaiKhoanLayout.setVerticalGroup(
            QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnLamMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoanQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVaiTroQLTK)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyTaiKhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat2)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa2)
                        .addGap(109, 109, 109))))
        );

        jPanel4.add(QuanLyTaiKhoan, "card6");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("THỐNG KÊ");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel15)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        jPanel4.add(ThongKe, "card7");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 988, 484));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuMouseClicked
        // TODO add your handling code here:
        openMenu();
    }//GEN-LAST:event_openMenuMouseClicked

    private void lbDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDongMouseClicked
        // TODO add your handling code here:
        closeMenu();
    }//GEN-LAST:event_lbDongMouseClicked

    private void lbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(true);
        QuanLySanPham.setVisible(false);
        QuanLyDonHang.setVisible(false);
        QuanLyTaiKhoan.setVisible(false);
        ThongKe.setVisible(false);
    }//GEN-LAST:event_lbTrangChuMouseClicked

    private void lbQuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLySanPhamMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        QuanLySanPham.setVisible(true);
        QuanLyDonHang.setVisible(false);
        QuanLyTaiKhoan.setVisible(false);
        ThongKe.setVisible(false);
        loadTableSach();
    }//GEN-LAST:event_lbQuanLySanPhamMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked
        // TODO add your handling code here:
        DangNhapUI dn = new DangNhapUI();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbDangXuatMouseClicked

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
        loadTableSach();
        delTextTbSach();
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> timSach = new ArrayList<>();
        for (Sach item : SachDAL.listSach()) {
            if (item.getTenSach().equalsIgnoreCase(txtTim1.getText())) {
                timSach.add(item);
            }
        }
        tbSach.setModel(new SachBLL(timSach));
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked
        // TODO add your handling code here:
        chonDongTbSach();
    }//GEN-LAST:event_tbSachMouseClicked

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        try {
            Sach s = new Sach();
            s.setMaSach(txtMaSach1.getText());
            s.setTenSach(txtTenSach1.getText());
            s.setTacGia(txtTacGia1.getText());
            s.setNhaXuatBan(txtNhaXuatBan1.getText());
            s.setNamXuatBan(Integer.parseInt(txtNamXuatBan1.getText()));
            s.setSoTrang(Integer.parseInt(txtSoTrang1.getText()));
            s.setDonGia(Double.parseDouble(txtDonGia1.getText()));
            s.setSoLuongCon(Integer.parseInt(txtSoLuongCon1.getText()));
            if (SachDAL.insert(SachDAL.listSach(), s)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm sách thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableSach();
                delTextTbSach();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        if (SachDAL.listSach().size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin để xóa");
        } else {
            try {
                Sach s = new Sach();
                s.setMaSach(txtMaSach1.getText());
                if (SachDAL.delete(SachDAL.listSach(), s)) {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    loadTableSach();
                    delTextTbSach();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed
        try {
            Sach s = new Sach();
            s.setMaSach(txtMaSach1.getText());
            s.setTenSach(txtTenSach1.getText());
            s.setTacGia(txtTacGia1.getText());
            s.setNhaXuatBan(txtNhaXuatBan1.getText());
            s.setNamXuatBan(Integer.parseInt(txtNamXuatBan1.getText()));
            s.setSoTrang(Integer.parseInt(txtSoTrang1.getText()));
            s.setDonGia(Double.parseDouble(txtDonGia1.getText()));
            s.setSoLuongCon(Integer.parseInt(txtSoLuongCon1.getText()));
            if (SachDAL.update(SachDAL.listSach(), s)) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableSach();
                delTextTbSach();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng số: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi :" + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void lbQuanLyTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyTaiKhoanMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        QuanLySanPham.setVisible(false);
        QuanLyDonHang.setVisible(false);
        QuanLyTaiKhoan.setVisible(true);
        ThongKe.setVisible(false);
        loadTableTaiKhoan();
    }//GEN-LAST:event_lbQuanLyTaiKhoanMouseClicked

    private void lbThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongKeMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        QuanLySanPham.setVisible(false);
        QuanLyDonHang.setVisible(false);
        QuanLyTaiKhoan.setVisible(false);
        ThongKe.setVisible(true);
    }//GEN-LAST:event_lbThongKeMouseClicked

    private void lbQuanLyDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuanLyDonHangMouseClicked
        // TODO add your handling code here:
        TrangChu.setVisible(false);
        QuanLySanPham.setVisible(false);
        QuanLyDonHang.setVisible(true);
        QuanLyTaiKhoan.setVisible(false);
        ThongKe.setVisible(false);
    }//GEN-LAST:event_lbQuanLyDonHangMouseClicked

    private void btnTim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim2ActionPerformed
        // TODO add your handling code here:
        ArrayList<TaiKhoan> timTK = new ArrayList<>();
        for (TaiKhoan item : TaiKhoanDAL.listTaiKhoan()) {
            if (item.getMaTK().equalsIgnoreCase(txtTimQLTK.getText())) {
                timTK.add(item);
            }
        }
        tbTaiKhoan.setModel(new TaiKhoanBLL(timTK));
    }//GEN-LAST:event_btnTim2ActionPerformed

    private void btnLamMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi2ActionPerformed
        // TODO add your handling code here:
        loadTableTaiKhoan();
        delTextTbTaiKhoan();
    }//GEN-LAST:event_btnLamMoi2ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        try {
            TaiKhoan tk = new TaiKhoan();
            tk.setMaTK(txtTaiKhoanQLTK.getText());
            tk.setMatKhau(txtMatKhauQLTK.getText());
            tk.setVaiTro(txtVaiTroQLTK.getText());
            if (TaiKhoanDAL.insert(TaiKhoanDAL.listTaiKhoan(), tk)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm tài khoản thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableTaiKhoan();
                delTextTbTaiKhoan();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng vai trò ! 0: Khách hàng. 1: Admin", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnCapNhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat2ActionPerformed
        // TODO add your handling code here:
        try {
            TaiKhoan tk = new TaiKhoan();
            tk.setMaTK(txtTaiKhoanQLTK.getText());
            tk.setMatKhau(txtMatKhauQLTK.getText());
            tk.setVaiTro(txtVaiTroQLTK.getText());
            int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn cập nhật ?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (rs == JOptionPane.YES_OPTION) {
                if (TaiKhoanDAL.update(TaiKhoanDAL.listTaiKhoan(), tk)) {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật tài khoản thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    if (DangNhapUI.username.equals(tk.getMaTK())) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng đăng nhập lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        DangNhapUI dn = new DangNhapUI();
                        dn.setVisible(true);
                        this.dispose();
                    }
                    loadTableTaiKhoan();
                    delTextTbTaiKhoan();
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng vai trò ! 0: Khách hàng. 1: Admin ", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhat2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        try {
            TaiKhoan tk = new TaiKhoan();
            tk.setMaTK(txtTaiKhoanQLTK.getText());
            int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa ?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (rs == JOptionPane.YES_OPTION) {
                if (!DangNhapUI.username.equals(tk.getMaTK())) {
                    if (TaiKhoanDAL.delete(TaiKhoanDAL.listTaiKhoan(), tk)) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        loadTableTaiKhoan();
                        delTextTbTaiKhoan();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn không thể xóa tài khoản của chính mình", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void tbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTaiKhoanMouseClicked
        // TODO add your handling code here:
        chonDongTbTaiKhoan();
    }//GEN-LAST:event_tbTaiKhoanMouseClicked

    public void delTextTbSach() {
        txtMaSach1.setText("");
        txtTenSach1.setText("");
        txtTacGia1.setText("");
        txtNhaXuatBan1.setText("");
        txtNamXuatBan1.setText("");
        txtSoTrang1.setText("");
        txtDonGia1.setText("");
        txtSoLuongCon1.setText("");
        txtTim1.setText("");
    }

    public void delTextTbTaiKhoan() {
        txtTaiKhoanQLTK.setText("");
        txtMatKhauQLTK.setText("");
        txtVaiTroQLTK.setText("");
        txtTimQLTK.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyDonHang;
    private javax.swing.JPanel QuanLySanPham;
    private javax.swing.JPanel QuanLyTaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JButton btnCapNhat1;
    private javax.swing.JButton btnCapNhat2;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnLamMoi2;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnTim2;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbDong;
    private javax.swing.JLabel lbQuanLyDonHang;
    private javax.swing.JLabel lbQuanLySanPham;
    private javax.swing.JLabel lbQuanLyTaiKhoan;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JLabel openMenu;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTable tbSach;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtMaSach1;
    private javax.swing.JTextField txtMatKhauQLTK;
    private javax.swing.JTextField txtNamXuatBan1;
    private javax.swing.JTextField txtNhaXuatBan1;
    private javax.swing.JTextField txtSoLuongCon1;
    private javax.swing.JTextField txtSoTrang1;
    private javax.swing.JTextField txtTacGia1;
    private javax.swing.JTextField txtTaiKhoanQLTK;
    private javax.swing.JTextField txtTenSach1;
    private javax.swing.JTextField txtTim1;
    private javax.swing.JTextField txtTimQLTK;
    private javax.swing.JTextField txtVaiTroQLTK;
    // End of variables declaration//GEN-END:variables
}
